# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
relative_permalinks: true

# Setup
title:               Jasmin Rubinovitz
tagline:             'MIT 4s50 - Information Design'
description:         'MIT 4.s50 Information Design: Exploration, Navigation, and Understanding - Jasmin Rubivnotiz'
url:                  http://jasrub.github.io
baseurl:              /4s50-information-deisgn
#paginate:            5

# About/contact
author:
  name:              Jasmin Rubivnoitz
  url:               http://jasrub.github.io
  email:             jasrub@media.mit.edu

# Custom vars
version:             1.0.0
