
permalink:           none

# Setup
title:               Jasmin Rubinovitz
tagline:             'MIT 4s50 - Information Design'
description:         'Information Design: Exploration, Navigation, and Understanding <br/> <br/> MIT 4.s50 Spring 2016'
url:                  http://jasrub.github.io
baseurl:              /4s50-information-deisgn
#paginate:            5

# About/contact
author:
  name:              Jasmin Rubivnoitz
  url:               http://jasrub.github.io
  email:             jasrub@media.mit.edu

# Custom vars
version:             1.0.0
